-- Rename `sheet_sync_jobs` -> `sheet_logging_jobs` and align the codebase on
-- "sheet logging" as the only name for the optional append-to-spreadsheet
-- pipeline. The column shape is identical; only the table name changes.
--
-- Old name was a leftover from the Phase-1 design where this queue drove a
-- full bidirectional Sheets sync. The post-3D system only ever appends, and
-- "sync" reads as "two-way reconciliation" elsewhere in the codebase, which
-- is misleading.
--
-- DuckDB supports `ALTER TABLE ... RENAME TO` for tables without dependent
-- foreign keys pointing at them; nothing else references `sheet_sync_jobs`,
-- so a single ALTER is enough.
--
-- Rollout note: budget migrations are applied lazily by
-- `duckdb_repo.get_budget_connection(year)` -> `init_budget_db(year)`
-- the *first time* each year's `budget_<year>.duckdb` is opened in the
-- new build. Concretely:
--   * the periodic drain_pending task opens every year that has pending
--     queue rows, so each such year is migrated on its first sweep;
--   * years with no pending rows stay on the old schema until they're
--     touched (next expense, next read, next rebuild). That's safe
--     because nothing in the new code references `sheet_sync_jobs` and
--     the rename is a no-op for query semantics.
-- If you need to force-migrate every year DB at once, run
-- `inv migrate-budget --year=YYYY` for each year.

ALTER TABLE sheet_sync_jobs RENAME TO sheet_logging_jobs;
