"""VM2 (Litestream replica) bootstrap and resync tasks.

Three layers, all routed through this module:

* Pure script builders (``_build_setup_replica_*``) — emit the bash
  blobs that VM2 ultimately runs. Tests pin their observable contract.
* :func:`setup_replica` — the orchestrator that wires the four
  bootstrap steps (packages, dir, swap, ssh hardening) and configures
  VM1's Litestream replicator to push to VM2.
* :func:`replica_resync` — post-restore housekeeping that resets the
  replica's WAL position by deleting its stale DB copy and restarting
  litestream so it pulls a fresh restore.
"""

from pathlib import Path

from invoke import task

from .backups_yandex import ensure_yandex_rclone_configured
from .constants import (
    _REMOTE_DB_PATH,
    BACKUP_FILENAME_PREFIX,
    BACKUP_FILENAME_SUFFIX,
    BACKUP_RCLONE_PATH,
    BACKUP_RCLONE_REMOTE,
    BACKUP_RETENTION_DAILY,
    BACKUP_RETENTION_MONTHLY,
    BACKUP_RETENTION_SCRIPT_PATH,
    BACKUP_RETENTION_WEEKLY,
    BACKUP_SCRIPT_PATH,
    BACKUP_SERVICE_PATH,
    BACKUP_TIMER_PATH,
    LITESTREAM_SERVICE,
    LITESTREAM_SNAPSHOT_INTERVAL,
    REMOTE_LITESTREAM_CONFIG_PATH,
    REPLICA_DB_NAME,
    REPLICA_LITESTREAM_DIR,
    VM1_LITESTREAM_KEY_PATH,
)
from .env import litestream_retention, replica_host
from .ssh_utils import (
    build_add_known_host_script,
    build_ensure_vm1_replica_key_script,
    build_harden_sshd_script,
    build_install_authorized_key_script,
    build_install_fail2ban_script,
    build_reset_known_host_script,
    build_setup_swap_script,
    create_service,
    litestream_install_script,
    ssh_capture,
    ssh_replica,
    ssh_run,
    ssh_sudo,
    write_remote_file,
    write_remote_replica_file,
)


def _replica_sftp_host() -> str:
    """Return the bare hostname for ssh-keyscan, derived from ``DINARY_REPLICA_HOST``.

    Strips the ``user@`` prefix so the result matches what Litestream
    puts in known_hosts (host only, no user, no port).
    """
    return replica_host().split("@", 1)[-1]


def _build_litestream_config() -> str:
    """Generate ``/etc/litestream.yml`` content from ``.deploy/.env`` + constants.

    All values are derived automatically — no manual template to fill in:
    - SFTP host + user: parsed from ``DINARY_REPLICA_HOST``
    - key-path: ``VM1_LITESTREAM_KEY_PATH`` (constant, generated once by
      ``inv setup-replica``)
    - path: ``REPLICA_LITESTREAM_DIR/REPLICA_DB_NAME`` (constant)
    - retention: ``DINARY_LITESTREAM_RETENTION`` from ``.deploy/.env``
      (default ``168h``)
    """
    rhost = replica_host()
    if "@" in rhost:
        user, host_part = rhost.split("@", 1)
    else:
        user = "ubuntu"
        host_part = rhost
    return (
        "# Generated by inv setup-replica. Do not edit by hand.\n"
        "\n"
        "snapshot:\n"
        f"  interval: {LITESTREAM_SNAPSHOT_INTERVAL}\n"
        f"  retention: {litestream_retention()}\n"
        "\n"
        "dbs:\n"
        f"  - path: {_REMOTE_DB_PATH}\n"
        "    replica:\n"
        "      type: sftp\n"
        f"      host: {host_part}:22\n"
        f"      user: {user}\n"
        f"      key-path: {VM1_LITESTREAM_KEY_PATH}\n"
        f"      path: {REPLICA_LITESTREAM_DIR}/{REPLICA_DB_NAME}\n"
    )


def _build_setup_replica_packages_script() -> str:
    """Emit the apt step of the replica bootstrap.

    Kept as a pure helper so tests can pin the observable contract
    (non-interactive apt, explicit ``unattended-upgrades`` install)
    without mocking SSH.

    ``DEBIAN_FRONTEND=noninteractive`` is required: without it
    ``apt-get install`` on a fresh Ubuntu cloud image can block on a
    postfix / grub debconf prompt that the replica never answers,
    turning the bootstrap into a silent hang.
    """
    return (
        "sudo bash <<'DINARY_REPLICA_PKG_EOF'\n"
        "set -euo pipefail\n"
        "export DEBIAN_FRONTEND=noninteractive\n"
        "apt-get update -qq\n"
        "apt-get install -y -qq unattended-upgrades\n"
        "DINARY_REPLICA_PKG_EOF\n"
    )


def _build_setup_replica_litestream_dir_script() -> str:
    """Emit the ``/var/lib/litestream`` provisioning step.

    Pinned via :data:`REPLICA_LITESTREAM_DIR` so the ``inv
    litestream-setup`` replica URL on VM1 and the directory created
    here on VM2 cannot drift apart silently.

    Mode ``0750`` with ``ubuntu:ubuntu`` ownership lets the SFTP
    receiver (logged in as ``ubuntu``) write WAL segments without
    granting world-read to the replica stream, which contains full
    row data pre-compaction.
    """
    return (
        "sudo bash <<'DINARY_REPLICA_DIR_EOF'\n"
        "set -euo pipefail\n"
        f"mkdir -p {REPLICA_LITESTREAM_DIR}\n"
        f"chown ubuntu:ubuntu {REPLICA_LITESTREAM_DIR}\n"
        f"chmod 750 {REPLICA_LITESTREAM_DIR}\n"
        f"ls -ld {REPLICA_LITESTREAM_DIR}\n"
        "DINARY_REPLICA_DIR_EOF\n"
    )


def _build_setup_replica_backup_packages_script() -> str:
    """Emit the apt step that installs backup tools on VM2 (rclone, sqlite3, zstd)."""
    return (
        "sudo bash <<'DINARY_BACKUP_PKG_EOF'\n"
        "set -euo pipefail\n"
        "export DEBIAN_FRONTEND=noninteractive\n"
        "apt-get update -qq\n"
        "apt-get install -y -qq python3 rclone sqlite3 zstd\n"
        "DINARY_BACKUP_PKG_EOF\n"
    )


def _build_backup_script() -> str:
    """Emit the ``/usr/local/bin/dinary-backup`` bash script for VM2.

    Flow: litestream restore → integrity_check → zstd → rclone copyto yandex: → retention prune.
    ``set -euo pipefail`` + trap ensures a failed restore never leaks temp files
    or overwrites Yandex history with a corrupt snapshot.
    """
    replica_path = f"{REPLICA_LITESTREAM_DIR}/{REPLICA_DB_NAME}"
    remote_prefix = f"{BACKUP_RCLONE_REMOTE}:{BACKUP_RCLONE_PATH}"
    return f"""#!/usr/bin/env bash
# Managed by inv setup-replica. Overwritten on every re-apply.
set -euo pipefail

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

SNAP="$WORKDIR/dinary.db"
CFG="$WORKDIR/litestream-restore.yml"

cat > "$CFG" <<YAML
dbs:
  - path: $SNAP
    replicas:
      - type: file
        path: {replica_path}
YAML

litestream restore -config "$CFG" "$SNAP"

if ! sqlite3 "$SNAP" 'PRAGMA integrity_check' | grep -qx 'ok'; then
    echo "integrity_check FAILED on restored snapshot" >&2
    exit 1
fi

zstd -q -19 "$SNAP" -o "$SNAP.zst"

TS=$(date -u +%Y-%m-%dT%H%MZ)
REMOTE="{remote_prefix}/{BACKUP_FILENAME_PREFIX}$TS{BACKUP_FILENAME_SUFFIX}"
rclone copyto "$SNAP.zst" "$REMOTE"

{BACKUP_RETENTION_SCRIPT_PATH} \\
    --remote "{remote_prefix}/" \\
    --prefix "{BACKUP_FILENAME_PREFIX}" \\
    --suffix "{BACKUP_FILENAME_SUFFIX}" \\
    --daily {BACKUP_RETENTION_DAILY} \\
    --weekly {BACKUP_RETENTION_WEEKLY} \\
    --monthly {BACKUP_RETENTION_MONTHLY}
"""


def _build_backup_service_unit() -> str:
    """Emit the ``dinary-backup.service`` systemd oneshot unit for VM2."""
    return (
        "# Managed by inv setup-replica. Overwritten on every re-apply.\n"
        "[Unit]\n"
        "Description=Back up dinary replica to Yandex.Disk\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        "User=ubuntu\n"
        f"ExecStart={BACKUP_SCRIPT_PATH}\n"
        "Nice=10\n"
        "IOSchedulingClass=best-effort\n"
        "IOSchedulingPriority=7\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def _build_backup_timer_unit() -> str:
    """Emit the ``dinary-backup.timer`` systemd unit for VM2.

    03:17 UTC with 30m jitter: avoids top-of-hour Litestream snapshot
    cadence on VM1, and ``Persistent=true`` catches missed runs after
    a reboot-during-scheduled-slot so the 24h retention gap cannot
    silently open.
    """
    return (
        "# Managed by inv setup-replica. Overwritten on every re-apply.\n"
        "[Unit]\n"
        "Description=Daily dinary off-site backup\n"
        "\n"
        "[Timer]\n"
        "OnCalendar=*-*-* 03:17:00\n"
        "RandomizedDelaySec=30m\n"
        "Persistent=true\n"
        "\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )


@task(name="setup-replica")
def setup_replica(c, swap_size_gb=1, no_swap=False):
    """Bootstrap VM2 (Litestream SFTP replica) and configure VM1 to replicate to it.

    VM2 is intentionally minimal: no Python app, no dinary service. Its only
    job is to accept WAL segments over SFTP from VM1's ``litestream.service``.

    Preconditions:

    * ``DINARY_REPLICA_HOST`` is set in ``.deploy/.env`` — VM2's public
      SSH endpoint.  All other Litestream config values (key path, replica
      dir, snapshot interval, retention) are derived from constants and
      ``DINARY_LITESTREAM_RETENTION``; no local ``litestream.yml`` file
      is needed or written.

    Idempotent: all VM2 steps short-circuit on re-apply. VM1→VM2 SSH
    trust (``authorized_keys``, ``known_hosts``) is installed once
    and *not* auto-refreshed — a VM re-provision is an explicit
    operator decision, handled by ``inv setup-reset-trust``.

    VM2's sshd stays bound to the public interface so the operator
    can ``ssh ubuntu@<public-ip>`` without a Tailscale hop; hardening
    (X11 off, root login off, fail2ban) is applied but ssh-tailscale-
    only is intentionally NOT — see ``.plans/cloud-security.md``.

    Flags:
        --swap-size-gb N   Swap size in gigabytes (default 1).
        --no-swap          Skip swap provisioning.
    """
    size = int(swap_size_gb)
    print(f"=== Installing baseline packages on {replica_host()} ===")
    ssh_replica(c, _build_setup_replica_packages_script())
    print(f"=== Hardening sshd on {replica_host()} ===")
    ssh_replica(c, build_harden_sshd_script())
    print(f"=== Installing fail2ban on {replica_host()} ===")
    ssh_replica(c, build_install_fail2ban_script())
    print(f"=== Provisioning {REPLICA_LITESTREAM_DIR} ===")
    ssh_replica(c, _build_setup_replica_litestream_dir_script())
    if not no_swap:
        print("=== Allocating swap on VM2 ===")
        ssh_replica(c, build_setup_swap_script(size_gb=size))

    print(f"=== Installing backup packages (rclone, sqlite3, zstd) on {replica_host()} ===")
    ssh_replica(c, _build_setup_replica_backup_packages_script())
    print(f"=== Installing Litestream binary on {replica_host()} ===")
    ssh_replica(c, litestream_install_script())

    print(f"=== Configuring Yandex.Disk rclone remote on {replica_host()} ===")
    ensure_yandex_rclone_configured(c)

    print(f"=== Installing backup script on {replica_host()} ===")
    write_remote_replica_file(c, BACKUP_SCRIPT_PATH, _build_backup_script())
    ssh_replica(c, f"sudo chmod 0755 {BACKUP_SCRIPT_PATH}")
    retention_src = (
        Path(__file__).parent.parent / "src/dinary/tools/backup_retention.py"
    ).read_text(encoding="utf-8")
    write_remote_replica_file(c, BACKUP_RETENTION_SCRIPT_PATH, retention_src)
    ssh_replica(c, f"sudo chmod 0755 {BACKUP_RETENTION_SCRIPT_PATH}")
    write_remote_replica_file(c, BACKUP_SERVICE_PATH, _build_backup_service_unit())
    write_remote_replica_file(c, BACKUP_TIMER_PATH, _build_backup_timer_unit())
    ssh_replica(c, "sudo systemctl daemon-reload")
    ssh_replica(c, "sudo systemctl enable --now dinary-backup.timer")

    print("=== Configuring VM1 Litestream replicator ===")
    content = _build_litestream_config()

    print("=== Establishing VM1→VM2 SSH trust for Litestream SFTP ===")
    pubkey = ssh_capture(c, build_ensure_vm1_replica_key_script()).strip()
    ssh_replica(c, build_install_authorized_key_script(pubkey))
    ssh_run(c, build_add_known_host_script(_replica_sftp_host()))

    ssh_run(c, litestream_install_script())
    write_remote_file(c, REMOTE_LITESTREAM_CONFIG_PATH, content)
    ssh_sudo(
        c,
        f"bash -c 'chown root:root {REMOTE_LITESTREAM_CONFIG_PATH} "
        f"&& chmod 644 {REMOTE_LITESTREAM_CONFIG_PATH}'",
    )
    create_service(c, "litestream", LITESTREAM_SERVICE)
    ssh_run(
        c,
        "sleep 3 && systemctl is-active litestream && "
        "sudo journalctl -u litestream -n 20 --no-pager",
    )

    print("=== Replica bootstrap done ===")


@task(name="setup-reset-trust")
def replica_reset_trust(c):
    """Force-refresh VM1→VM2 SSH trust after an intentional VM reinstall.

    ``inv setup-replica`` installs trust once and refuses to
    auto-heal a host-key mismatch — an unexpected mismatch is a
    security signal, not a routine case. This task is the explicit
    operator statement "yes, VM2 was re-provisioned, the new host
    key is legitimate": it wipes VM2's entry from VM1's
    ``~/.ssh/known_hosts``, re-scans, and re-installs VM1's pubkey
    in ``~ubuntu/.ssh/authorized_keys`` on VM2 (idempotent — the
    old entry, if it remained from before reinstall, is left alone;
    a new one is appended if missing).

    Run after:
      * VM2 re-created from a fresh image
      * VM1 re-created (new ``id_ed25519``)
      * ``inv primary-rollback`` that materially changed VM1 state

    Does NOT touch the DB — pair with ``inv setup-resync`` when
    you also need to wipe VM2's ``/var/lib/litestream/dinary`` and
    re-seed from the primary.
    """
    lite_host = _replica_sftp_host()
    print(f"=== Resetting VM2 host key ({lite_host}) in VM1 known_hosts ===")
    ssh_run(c, build_reset_known_host_script(lite_host))
    print("=== Re-installing VM1 pubkey on VM2 authorized_keys ===")
    pubkey = ssh_capture(c, build_ensure_vm1_replica_key_script()).strip()
    ssh_replica(c, build_install_authorized_key_script(pubkey))
    print("=== Trust refreshed ===")


@task(name="setup-resync")
def replica_resync(c):
    """Resync the replica after a DB restore or WAL txid mismatch.

    Litestream runs on VM1 (not VM2). A resync stops the replicator on
    VM1, wipes the stale LTX tree on VM2 so litestream starts with a
    clean slate, then restarts the replicator on VM1 — it will push a
    fresh full snapshot to VM2 on the next WAL commit.

    Run after:
      * ``inv backup-cloud-restore`` restores a snapshot from Yadisk
        (primary DB now ahead/behind the replica txid counter).
      * The litestream journal shows "detected database behind replica"
        or repeated compaction failures that don't self-heal.

    Run automatically by ``inv backup-cloud-restore`` unless
    ``--no-resync`` is passed.
    """
    print("=== Stopping litestream on VM1 ===")
    ssh_run(c, "sudo systemctl stop litestream")
    print(f"=== Wiping stale LTX tree on {replica_host()} ===")
    ssh_replica(c, f"rm -rf {REPLICA_LITESTREAM_DIR}/{REPLICA_DB_NAME}")
    print("=== Starting litestream on VM1 (will push fresh snapshot) ===")
    ssh_run(c, "sudo systemctl start litestream")
    ssh_run(
        c,
        "sleep 5 && systemctl is-active litestream && "
        "sudo journalctl -u litestream -n 20 --no-pager",
    )
    print("=== Replica resync done ===")
