DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS sheet_logging_jobs;
DROP TABLE IF EXISTS expense_tags;
DROP TABLE IF EXISTS expenses;
DELETE FROM app_metadata WHERE key = 'catalog_version';
DROP TABLE IF EXISTS app_metadata;
DROP TABLE IF EXISTS sheet_mapping_tags;
DROP TABLE IF EXISTS sheet_mapping;
DROP TABLE IF EXISTS import_mapping_tags;
DROP TABLE IF EXISTS import_mapping;
DROP TABLE IF EXISTS exchange_rates;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS category_groups;
